In [1]:
import numpy as np
import pandas as pd
import glob
import os 
os.chdir("/Users/KevinBu/Desktop/clemente_lab/iclust/")

In [11]:
df_otu = pd.read_csv('../CUTIE/data/enrica/filtered_otu_table_800_no_contaminants_CANCER_diagnosis_def_nosingletons_L6.txt', 
                     skiprows = 1, sep = '\t')
df_otu = df_otu.T
df_otu.columns = df_otu.iloc[0,:]
df_otu = df_otu.drop('#OTU ID')
#df_otu = df_otu.set_index(df_otu.iloc[:,0])
# df_otu = df_otu.reindex(df_meta.index)
df_otu.head()

#OTU ID,k__Archaea;p__Euryarchaeota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanobrevibacter,k__Archaea;p__Euryarchaeota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanosphaera,k__Archaea;p__Euryarchaeota;c__Thermoplasmata;o__E2;f__[Methanomassiliicoccaceae];g__vadinCA11,k__Archaea;p__[Parvarchaeota];c__[Parvarchaea];o__YLA114;f__;g__,k__Bacteria;p__Acidobacteria;c__Acidobacteria-6;o__iii1-15;f__;g__,k__Bacteria;p__Acidobacteria;c__Acidobacteria-6;o__iii1-15;f__mb2424;g__,k__Bacteria;p__Acidobacteria;c__Solibacteres;o__Solibacterales;f__;g__,k__Bacteria;p__Acidobacteria;c__[Chloracidobacteria];o__DS-100;f__;g__,k__Bacteria;p__Acidobacteria;c__[Chloracidobacteria];o__RB41;f__Ellin6075;g__,k__Bacteria;p__Actinobacteria;c__Acidimicrobiia;o__Acidimicrobiales;f__;g__,...,k__Bacteria;p__Tenericutes;c__Mollicutes;o__RF39;f__;g__,k__Bacteria;p__Verrucomicrobia;c__Verrucomicrobiae;o__Verrucomicrobiales;f__Verrucomicrobiaceae;g__,k__Bacteria;p__Verrucomicrobia;c__Verrucomicrobiae;o__Verrucomicrobiales;f__Verrucomicrobiaceae;g__Akkermansia,k__Bacteria;p__Verrucomicrobia;c__Verrucomicrobiae;o__Verrucomicrobiales;f__Verrucomicrobiaceae;g__Luteolibacter,k__Bacteria;p__Verrucomicrobia;c__Verrucomicrobiae;o__Verrucomicrobiales;f__Verrucomicrobiaceae;g__Prosthecobacter,k__Bacteria;p__Verrucomicrobia;c__[Pedosphaerae];o__[Pedosphaerales];f__auto67_4W;g__,k__Bacteria;p__Verrucomicrobia;c__[Spartobacteria];o__[Chthoniobacterales];f__[Chthoniobacteraceae];g__,k__Bacteria;p__[Thermi];c__Deinococci;o__Deinococcales;f__Trueperaceae;g__Truepera,k__Bacteria;p__[Thermi];c__Deinococci;o__Thermales;f__Thermaceae;g__Meiothermus,k__Bacteria;p__[Thermi];c__Deinococci;o__Thermales;f__Thermaceae;g__Thermus
CE45,0.0011796,0.00030273,0,0,0,0,0,0,0,0.000511509,...,0,0,0.0390208,0,0,0,0.000407119,0,0.000167023,0.00109609
AS35,0,0,0,0,0,0,0,0,0,0,...,0.00274861,0,1.86981e-05,0,0,0,0,0,0.000495498,0.000570291
IJ3A,0.000277373,0,0,0,0,0,0,0,0,0,...,0,0,0.0413009,0,0,0,0,0,1.38687e-05,0
IL39,0,0,0.00528881,0,0,0,0,0,0,0,...,0,0,0.0178757,0,0,0,0,0,0.00140881,0.00577381
IJ25A,0.00148645,1.11763e-05,0,0,0,0,0,0,0,0,...,0,0,0.0467505,0,0,0,0,0,0,3.35289e-05

In [12]:
df_meta = pd.read_csv('../CUTIE/data/enrica/mapping_file_Final_12.3.18.txt', 
                     sep = '\t')
df_meta = df_meta.set_index('#SampleID')
df_meta = df_meta.iloc[:,69:]
df_meta.head()

,T_omega_MCA,THCA,TCA,TUDCA,THDCA,X_7_12_diketoLCA,TCDCA,UCA,TDCA,Omega_MCA,...,CDCA,X_12_ketoLCA,NorDCA,dehydroLCA,alloLCA,isoLCA,LCA,DCA,isoDCA,GLCA
#SampleID,,,,,,,,,,,,,,,,,,,,,
IL1,29.4,31.9,0.3,0.5,1.8,15.1,899.1,4.4,947.3,11.7,...,1320.2,481.4,1.3,224.7,7.9,269.5,1868.4,859.2,1.5,0.2
IL2,3.9,32.4,59.3,44.6,19.7,14.4,318.5,4.2,71.4,5.4,...,50.2,10.1,1.0,1.3,6.2,44.6,2.4,41.3,2.7,0.4
IL3,6.7,39.0,0.2,1.5,1.3,4.5,410.0,94.7,178.2,7.8,...,9807.3,920.9,2.3,984.4,3.0,249.4,2772.4,4808.4,1.3,0.1
IL4,26.6,16.1,0.8,4.1,44.1,5.4,6178.1,0.7,7141.5,3.8,...,30.4,26.2,9.6,133.8,37.4,51.9,27.7,26.5,1.2,0.2
IL5,14.3,5.3,3.5,2.5,7.7,7.2,565.6,3.4,896.4,4.1,...,92.6,6.8,0.9,2.9,0.1,40.9,0.6,130.1,0.8,0.2

In [13]:
df_cyto = pd.read_csv('../CUTIE/data/enrica/Cytokines.txt', 
                     sep = '\t')
df_cyto = df_cyto.set_index('#SampleID')
df_cyto = df_cyto.iloc[:,4:]
df_cyto.head()

,IL1a,IL2Ra,IL3,IL12p40,IL16,IL18,CTACK,GROa,HGF,IFNa2,...,MIP1b,PDGFBB,RANTES,TNFa,VEGF,IL1b,IP-10,TGF-b1M,TGF2bM,TGF-b3M
#SampleID,,,,,,,,,,,,,,,,,,,,,
IJ1A,338.23,43.05,149.14,232,122.7,14.39,252.35,OOR,10121.56,98.05,...,26.02,126.42,17.62,150.3,9053.47,221.71,150.69,138.6,121.66,131.71
IJ2A,4.20,22.38,37.60,76.38,2.61,2.05,72.81,OOR,70.82,18.47,...,OOR,6.38,1.79,OOR,15.79,OOR,OOR,731.46,439.14,519.87
IJ3A,545.81,26.16,42.09,OOR,2.61,1.81,45.26,OOR,1219.73,71.73,...,OOR,2.86,OOR,OOR,10.48,2.73,66.74,5.01,5.05,OOR
IJ4A,129.98,12.86,33.01,OOR,OOR,1.35,OOR,OOR,2347.84,27.38,...,1.19,2.86,OOR,OOR,551.79,1.04,13.6,OOR,5.05,OOR
IJ5A,261.20,16.68,37.60,OOR,OOR,0.88,OOR,OOR,2677.61,44.63,...,1.52,4.6,0.76,OOR,589.09,3.67,54.82,OOR,5.29,OOR

In [14]:
# df_otu_cyto
# df_otu_cyto: subset of df_otu that overlaps with cyto
indices = [value for value in df_otu.index.values if value in df_cyto.index.values] 
df_otu_cyto = df_otu.loc[indices,:]
df_otu_cyto.to_csv('../CUTIE/data/enrica/df_otu_cyto_nosingletons.txt', sep = '\t')

# df_cyto_otu: subset of df_cyto that overlaps with otu
df_cyto_otu = df_cyto.loc[indices,:]
df_cyto_otu.to_csv('../CUTIE/data/enrica/df_cyto_otu_nosingletons.txt', sep = '\t')

In [15]:
# df_otu_meta
# df_otu_meta: subset of df_otu that overlaps with meta
indices = [value for value in df_otu.index.values if value in df_meta.index.values] 
df_otu_meta = df_otu.loc[indices,:]
df_otu_meta.to_csv('../CUTIE/data/enrica/df_otu_meta_nosingletons.txt', sep = '\t')

# df_meta_otu: subset of df_meta that overlaps with otu
df_meta_otu = df_meta.loc[indices,:]
df_meta_otu.to_csv('../CUTIE/data/enrica/df_meta_otu_nosingletons.txt', sep = '\t')