In [1]:
import pandas as pd
from glob import glob
import numpy as np
import os

In [12]:
traj_files = glob('/Users/KevinBu/Desktop/clemente_lab/iclust/data/lodi/*.tsv')

In [13]:
for f in traj_files:
    taxa = os.path.splitext(os.path.basename(f))[0]
    whole_df = pd.read_csv(f, sep='\t')
    whole_df = whole_df[['X','Y','ID']]
    os.mkdir('/Users/KevinBu/Desktop/clemente_lab/iclust/data/lodi_trajs/' + taxa + '/')
    taxa_df = pd.DataFrame(columns=['x','y','ID'])
    for index, row in whole_df.iterrows():
        ID = str(row['ID'])
        df = pd.DataFrame(columns=['x','y','ID'])
        df['x'] = np.array([float(x) for x in row['X'].split(',')])
        df['y'] = np.array([float(x) for x in row['Y'].split(',')])
        df['ID'] = ['s' + str(row['ID'])] * len(df)
        taxa_df = taxa_df.append(df)
    taxa_df.to_csv('/Users/KevinBu/Desktop/clemente_lab/iclust/data/lodi_trajs/' + taxa + '/lodi_noninterp_' + taxa + '.txt',sep='\t', index=False)

In [4]:
df = pd.read_csv(traj_files[2], sep='\t')

In [5]:
df.head()

,ID,X,Y,BarcodeSequence,Description,abx1_pmp_all_bymonth,abx_all_sources,abx_ever,abx_name,abx_pmp_all,...,noise,original_trajectory,run_date,run_prefix,sample_summary,samplewell,sex,short_taxa,studyid,taxa
0,9446,"0.0,1.2,2.4,3.5999999999999996,4.8,6.0,7.19999...","3.0137017807410206e-06,3.0513874802360444e-06,...",CTTGCATACCGG,Cesarean.bd.n.1,NaN,1,1,NaN,NaN,...,0.0,46,2/27/15,SeqRun5,Cesarean.bd.n.1,P12.D03,Female,Gardnerella,46,k__Bacteria;p__Actinobacteria;c__Actinobacteri...
1,6844,"0.0,1.375,2.75,4.125,5.5,6.875,8.25,9.625,11.0...","1.784817460157894e-05,5.778028276093296e-05,0....",GTTATCGCATGG,Vaginal.bd.n.0,NaN,0,0,NaN,NaN,...,0.0,44,10/20/14,SeqRun4,Vaginal.bd.n.0,P08.F02,Male,Gardnerella,44,k__Bacteria;p__Actinobacteria;c__Actinobacteri...
2,6845,"0.0,1.3333333333333333,2.6666666666666665,4.0,...","0.0,3.2432761823997057e-06,1.4924288623292048e...",ACGCTGTCGGTT,Vaginal.bd.n.0,NaN,0,0,NaN,NaN,...,0.0,45,2/27/15,SeqRun5,Vaginal.bd.n.0,P12.E10,Male,Gardnerella,45,k__Bacteria;p__Actinobacteria;c__Actinobacteri...
3,7443,"0.0,1.3333333333333333,2.6666666666666665,4.0,...","0.0,1.3480936833605302e-05,9.950679884592408e-...",ACCCAAGCGTTA,Vaginal.fd.y.1,post,1,1,Amoxicillin,post,...,0.0,43,2/27/15,SeqRun5,Vaginal.fd.y.1,P15.D02,Female,Gardnerella,43,k__Bacteria;p__Actinobacteria;c__Actinobacteri...
4,10241,"0.0,1.0909090909090908,2.1818181818181817,3.27...","8.224892152575799e-06,1.2919396376858798e-05,1...",TACTCGGGAACT,Vaginal.bd.y.1,NaN,1,1,NaN,NaN,...,0.0,41,10/20/14,SeqRun4,Vaginal.bd.y.1,P08.B06,Male,Gardnerella,41,k__Bacteria;p__Actinobacteria;c__Actinobacteri...